### ISSUE TITLE
[webOS] TypeError at bootstrap still present after PR #200 fix - LG MT49S webOS 6.10.60

### ISSUE THREAD

**Issue by busattoale** [NuvioMedia/NuvioWeb#245]
## Description
App still crashes at bootstrap before UI renders after the fix introduced in PR #200.

## Device info
- Device: LG MT49S
- webOS: 6.10.60
- Nuvio version: 0.2.6

## Error
TypeError: undefined is not a function
at c (app.bundle.js:1:11381)
at dt (app.bundle.js:1:46598)
at file (app.bundle.js:1:106076)
at Object.getForProfile
at Object.get
at Object.mt.get
at Qu (app.bundle.js:1:284925)
at file (app.bundle.js:1:288328)
at file (app.bundle.js:1:5531)
at h (app.bundle.js:1:1909)

## Notes
- Startup hit an error before the app UI rendered
- Previously reported in #195
- Related fix PR #200 did not resolve the issue for this device
