### PR TITLE
fix(runtime): app still crashes at bootstrap on old webOS (Number.isFinite / Math.trunc not a function)

### LINKED ISSUE #245: [webOS] TypeError at bootstrap still present after PR #200 fix - LG MT49S webOS 6.10.60
## Description
App still crashes at bootstrap before UI renders after the fix introduced in PR #200.

## Device info
- Device: LG MT49S
- webOS: 6.10.60
- Nuvio version: 0.2.6

## Error
TypeError: undefined is not a function
at c (app.bundle.js:1:11381)
at dt (app.bundle.js:1:46598)
at file (app.bundle.js:1:106076)
at Object.getForProfile
at Object.get
at Object.mt.get
at Qu (app.bundle.js:1:284925)
at file (app.bundle.js:1:288328)
at file (app.bundle.js:1:5531)
at h (app.bundle.js:1:1909)

## Notes
- Startup hit an error before the app UI rendered
- Previously reported in #195
- Related fix PR #200 did not resolve the issue for this device

### PR DESCRIPTION
**Pull request by jaydeep-pipaliya**
Fixes #245 (continuation of #195 / PR #200)

PR #200 added a good set of builtin polyfills but missed the Number and Math ES2015 statics. On the LG MT49S (webOS 6.10.60) those are still undefined, so the app crashes at bootstrap with "TypeError: undefined is not a function" in the profile store path - profileManager uses Number.isFinite and Math.trunc while reading the profile, which runs before the UI renders.

Added polyfills for the ones the codebase actually uses: Number.isFinite (53 files), Number.isInteger, Number.isNaN, Number.parseInt, Number.parseFloat, Number.MAX_SAFE_INTEGER, Number.MIN_SAFE_INTEGER and Math.trunc (24 files). They're defined first in polyfills.js because the existing Array.prototype.flat polyfill itself calls Number.isFinite.

Tested by removing those statics before the bundle loads to mimic the old engine: on main the app dies with 'App bootstrap failed: Number.isFinite is not a function' and renders nothing (matching the report); with this change the polyfills restore them and the app boots to the profile screen. Math.trunc verified against positive/negative/zero/NaN cases.

### CODE REVIEW

**Comment by jaydeep-pipaliya** [comment]
Stepping back a bit — this is the **fourth** time the same legacy-webOS bootstrap crash has come back:

- #195 → fixed by adding `Object.entries` etc. (PR #196)
- PR #200 → added more Object/Array/String/Promise builtins
- now #245 → still crashing, this time on `Number.isFinite` / `Math.trunc`

Each fix only patches the specific method that happened to crash this time, so the next unpolyfilled builtin just trips it up again on these old engines. It's whack-a-mole, and every round is a user whose app won't even start.

The repo is actually already set up for the permanent fix — the build has `useBuiltIns: "entry"` + `corejs: 3` in `scripts/build.mjs`, but there's no `import "core-js"`, so Babel injects **zero** core-js polyfills and we fall back to the hand-rolled list. Two clean ways to make it complete and automatic:

1. **`useBuiltIns: "usage"`** (one-line change in build.mjs) — Babel scans the bundle and injects only the polyfills actually used for the `chrome 38` target. No source import needed. Costs ~130KB raw in the bundle (much less gzipped), and ends the crash class for good — no more manual list to keep in sync.
2. **`import "core-js/stable"`** at the top of `js/app.js` — full coverage, slightly heavier.

I'd suggest option 1. The hand-rolled list can stay as-is (it's harmless), but `usage` mode means we stop shipping builds that don't boot on a device just because someone used a new builtin.

This PR fixes the immediate #245 crash so it's safe to merge now. But if you're open to it @WhiteGiso, I'm happy to open a follow-up PR switching to `useBuiltIns: "usage"` so we don't keep doing this every release. @anikettuli since you did #200, curious what you think.
